### ISSUE TITLE
a minor bug for calculating circRNA sequence length

### ISSUE THREAD

**Issue by JinwenBioinfo** [bioinfo-biols/CIRI-long#12]
Dear author,
There may be a minor bug in your script that circRNA exon length has been shortened by one nt.
e.g
isoform exon structure : 1-100, 201-300
actual length: 200
yours: 198

My annotation is from GENCODE, which is 1-based format.
The column `circ_len` of `CIRI.info` shows an incorrect value, an instance is as

circ_id | logFC | foldChange | PValue | pAdj | diffState | Chr_Start_End_Strand | circBankID | circbaseID | mouse_circRNA_ID | gene_id | gene_name | gene_type | strand | splice_site | circ_type | circ_len | isoform
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr7:129813472-129815449 | 2.858076 | 7.250479 | 0.023715 | 0.042994 | up | chr7_129813472_129815449_- | hsa_circTMEM209_032 | hsa_circ_0082343 | ENSG00000146842.12 | TMEM209 | protein_coding | - | AG-GT | exon | 308 | 129813472-129813569,129813665-129813779,129815352-129815449

Best wishes.

**Comment by Kevinzjy** [comment]
Hi @JinwenBioinfo , you're correct! We made a mistake when calculating the length from the isoform structure. I will fix it in the coming commit. Thanks for letting us know!
