### ISSUE TITLE
alternative splicing events detecting in different conditions

### ISSUE THREAD

**Issue by JinwenBioinfo** [bioinfo-biols/CIRI-long#17]
Hi,
is it a good strategy to detect differential alternative splicing events that I collapse the circRNAs for each sample and then compare ASs between conditions ?
E.g. I have 3 cancer samples and 3 normal samples. I would collapse circRNAs individually, then compare the ASs between the cancer and normal.

**Comment by Kevinzjy** [comment]
It's OK, but I believe collapsing all samples together should get better results.

**Comment by JinwenBioinfo** [comment]
Thanks.
