### ISSUE TITLE
Could CIRI-long detect f-circRNAs?

### ISSUE THREAD

**Issue by gnilihzeux** [bioinfo-biols/CIRI-long#6]
Recently, another strategy detecting circRNAs using Nanopore had published, which is [circFL-seq reveals full-length circular RNAs with rolling circular reverse transcription and nanopore sequencing].

The paper underlined the feature about f-circ, so could CIRI-long do the same ?

Thanks.

**Comment by Kevinzjy** [comment]
Well, although it's theoretically possible to detect f-circRNAs using our sequencing strategy, the current version of CIRI-long won't output these results. We could possibly add this feature in the future.

**Comment by gnilihzeux** [comment]
I See. Thank you.
