### ISSUE TITLE
Source code for libs/ccs?

### ISSUE THREAD

**Issue by rekado** [bioinfo-biols/CIRI-long#7]
The executable libs/css does not seem to have associated source code.  How can it be built from source?

**Comment by Kevinzjy** [comment]
Hi @rekado , the source code of libs/ccs is in a separate repository (https://github.com/Kevinzjy/circtools).

**Comment by rekado** [comment]
Perfect, thank you!

**Comment by rekado** [comment]
FYI: ciri-long is now available as a package in GNU Guix.  `guix install ciri-long` installs it alongside `ccs`, which is built from source.

**Comment by Kevinzjy** [comment]
> FYI: ciri-long is now available as a package in GNU Guix. `guix install ciri-long` installs it alongside `ccs`, which is built from source.

That's great ! Thanks for the help.
