### ISSUE TITLE
Confusing results that circ_len < 0

### ISSUE THREAD

**Issue by gnilihzeux** [bioinfo-biols/CIRI-long#8]
Dear author,

   Threre are some confusing results as the pic:
![企业微信截图_16372074866060](https://user-images.githubusercontent.com/4859358/142348677-e1bb6bd1-3565-4f81-bb78-db8b11e65fa8.png)

BTW, there are some other items which consused me
    1. The `*` after splice_site, what's that
    2. what is `equivalent_seq` (although your manual presents a little message)

Thanks.

**Comment by Kevinzjy** [comment]
Hi, @gnilihzeux these should be false-positive results from erroneous reads. You could filter this out from the final result. 

Besides, "*" after splice site refers to novel splice sites that are not annotated in the reference GTF, and equivalent_seq are the repetitive sequences in the back-splice junction region for debugging purposes.

**Comment by gnilihzeux** [comment]
That's very helpful. Thank you very much.
