### ISSUE TITLE
How to detect Alternative Splicing events ?

### ISSUE THREAD

**Issue by gnilihzeux** [bioinfo-biols/CIRI-long#9]
Dear author,
      
Could you please share your strategy that how to detect alternative splicing events ? There seems to be no clue in the paper. 

What I can think of is comparing circRNA exons model with known gene model. There is a schematic diagram of Exon Skipping below

```
Gene       -----------IIIIIIIIIIIIIIIIIIIII----------IIIIIIIIIIIIIIIIIIIII----------IIIIIIIIIIIIIIIIIIIIIIIII-------------
circRNA               IIIIIIIIIIIIIIIIIIIII                                         IIIIIIIIIIIIIIIIIIIIIIIII
```
But it's hard for me to achieve this especially for reads assignment to each exon.

So, is there any tool to implement this work, just like rMATS using in next-generation RNA-seq ?

Thanks a lot.

**Comment by Kevinzjy** [comment]
The alternative splicing events are annotated by customized scripts. We could release a future version to output the ratio of different isoforms in the same BSJ event.

**Comment by gnilihzeux** [comment]
Thanks. That would be great.
